### ISSUE TITLE
Assessment regions for Southern Ocean ecosystem 

### ISSUE THREAD

**Issue by jessmt** [AustralianAntarcticDivision/aceecostats#1]
Description of assessment regions for Southern Ocean ecosystem 
[Assessment map description.docx](https://github.com/AustralianAntarcticDivision/aceecostats/files/605306/Assessment.map.description.docx)

**Comment by mdsumner** [comment]
Refs still need a bit formatting wise: https://australianantarcticdivision.github.io/aceecostats/reference/aes_region.html 

Thanks!
