### ISSUE TITLE
terminology for zones: continent, high-latitude, mid latitude 

### ISSUE THREAD

**Issue by RTreb** [AustralianAntarcticDivision/aceecostats#10]
@mdsumner 

- [x] Terminology should be changed to continent, high-latitude, mid-latitude (i.e. no longer polar or temperate) throughout to remove ambiguity

**Comment by mdsumner** [comment]
Created new data sets `aes_zone` and `aes_zone_ll`, see `example(aes_zone)` for basic plot comparison.

**Comment by RTreb** [comment]
Readme needs to be updated with aes_zone (and is currently broken)
