### ISSUE TITLE
urgent figure updates

### ISSUE THREAD

**Issue by RTreb** [AustralianAntarcticDivision/aceecostats#11]
@mdsumner 

- [ ] Y-axis labelling: y axis labelling is urgently needed to allow development of statements comparing variability and change between regions

**Comment by mdsumner** [comment]
I've put a first stab here, with gratuitous labels for the total for comparison: 

https://github.com/AustralianAntarcticDivision/aceecostats/blob/master/inst/workflow/graphics/ice_DRAFT-001_y-axis.pdf

It's confusing what this means, but I think picking axis points based on the total area for the region is right here.  Needs checking

3617dced

**Comment by RTreb** [comment]
Are there any explanatory notes to accompany this? Maybe I'm being dim, but it is extremely confusing. Specifically:
- why are the axes labelled "mean"? Shouldn't this just be "area"?
- why are the axes decreasing? Doesn't moving higher up the y axis indicate a greater total area? Is this a mistake?
- In several panels, the lower y-axis label (which is the higher value) is larger than the total area. How is this possible (or is this an error in the exponents)?
