### ISSUE TITLE
figure updates

### ISSUE THREAD

**Issue by RTreb** [AustralianAntarcticDivision/aceecostats#12]
@mdsumner 
All plots
- [ ] colour coding for what time-period is represented by different shades in the “noodle” plots needs to be consistent across plots, inlcluding the Gantt chart

SST plots
- [ ] change shoulder season pairs to summer/spring and winter/autumn in sparklines as per previous versions of plots. Purpose of these sparklines is to show that the trends for summer/spring and winter/autumn are similar.

- [x] extend the x-axis to 30 degrees C so that distributions are not truncated

Chl-a plots
- [ ] mid-line for sparklines needs to match the width of the sparkline (chlorophyll)

**Comment by mdsumner** [comment]
Shoulder pairs now Summer/Autumn and Winter/Spring. r
