### ISSUE TITLE
output workflows 

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/aceecostats#14]
Process as at d376221e4143fb97cb51c1a401d96f257c3a22f4

* Scripts in inst/workflow/
* Figures in in inst/workflow/graphics/

- bulk extract process **01_bulk_aceeco.r**
- SST summary process **02_bulk_summ_SST.r**
- SST plot script **03_sst_plot.r**
- CHL summary process **02_bulk_summ_CHL.r**
- CHL plot script **03_chl_plot.r**

Output tables now in SQLite database which is here

```R
library(dplyr)
db <- src_sqlite("/mnt/acebulk/habitat_assessment_output.sqlite3")
```

The db has tables `sst_density_tab` and `sst_sparkline_tab`, `chl_density_tab` and `chl_sparkline_tab`. 

These are read in using `dpylr::src_sqlite` and `dplyr::tbl(db, [tablename])`, as per the plotting scripts. 

There is some mutate and rename for the database tables because 1) sqlite cannot store date-time type and round-trip 2) a rename and/or season classification is required because of slight differences between the SST/CHL (and because of the confusing redundancy between season/date/decade). 

Ice duration is not yet updated, but the plots are there and are probably ok. 

More info on dplyr and sqlite is available here: https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html

**Comment by mdsumner** [comment]
@RTreb

**Comment by RTreb** [comment]
This is awesome. I'll start working on updated plots for SST and Chl. In the mean time if you can update the process for ice duration @mdsumner, that would be great :)

**Comment by mdsumner** [comment]
Moving to a shiny world, with 00-pre-caching steps as well. This description will live in the readme.
