### ISSUE TITLE
updates  - ice duration

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/aceecostats#15]
* check density change for early decade
* change projection to highlight continent (probably long-lat)
* anomaly maps

**Comment by jessmt** [comment]
- Also check difference between duration maps calculated from (day of retreat - day of advance) and count(# days with ice > 15%). The latter may actually be better for our purposes so may make sense to migrate to this form.

**Comment by jessmt** [comment]
- missing value tabulation
- chl from bins
- proportion days ice
