### ISSUE TITLE
Region labelling in ggplot example in readme

### ISSUE THREAD

**Issue by RTreb** [AustralianAntarcticDivision/aceecostats#7]
Region labelling is and colour coding are incorrect in the ggplot example. Needs to be update to use aes_region_simple; but this will require and ID column to be included in aes_region_simple

**Comment by mdsumner** [comment]
We now have `aes_zone` and have normalized to `Zone` and `SectorName` as per https://github.com/AustralianAntarcticDivision/aceecostats/issues/10
