### ISSUE TITLE
graphics workflows

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/aceecostats#8]
Locations of workflow scripts and outputs are described below. 

## re-working process 2017-03-07

Artefacts "decadal_tabs.rds" and "sparky_line.rds" are in /home/[username]/ on the temporary server. 

These are both tibbles, read with "readRDS", i.e. 

```{r}
library(ggplot2)
library(tidyr)
sp_line <- readRDS("sparky_line.rds")
## we can chain this all into ggplot interactively
## gather is a reshape so "measure" is key on "min" or "max", and "sst" is the value
## we keep SectorName, Zone, season_year out of the reshape, and we filter/facet on them
spark_data <- sp_line %>% filter(Zone == "High-Latitude", aes_season(season_year) == "Winter") %>% 
  gather(measure, sst, -SectorName, -Zone, -season_year)
  
## the plot call is general, after we've reshaped and filterered above
ggplot(spark_data, aes(x = season_year, y = sst, group = measure, colour = measure)) + geom_line() + facet_wrap(~SectorName+ Zone)


big_tab <- readRDS("decadal_tabs.rds")
density_data <- big_tab %>% filter(Zone == "Mid-Latitude", season == "Summer") 
ggplot(density_data, aes(x = min, weights = area,  group = decade, colour = decade)) + 
  geom_density() + facet_wrap(~SectorName+ Zone) 
```
## plots

The  .pdf files produced by the scripts: 
```
inst/workflow/graphics/
```

##  Processing workflows 

Scripts are in

```
inst/workflow/
```

* **01** *01_bulk_aceeco.r* - the bulk extraction to cache
* **02** *02_bulk_summ_duration.r, 02_bulk_summ.r* - summaries into regions and decades
* **03** *03_chl_plot.r, 03_seaice-duration-plot.r, 03_sst_plot.r* - plots of each variable

Note: currently 2) gets split across a for loop and different scripts to deal with the size of individual subsets, which sometimes cause problems for specific machines. It's a bit dynamic to avoid needless copying of data around the network, but will be sorted out eventually. 

## bulk data preparation

Bulk cache data is in
```
/mnt/acebulk
```

The .grd/.gri pairs are the raster templates, the .feather files are tables of variable min/max summaries, and some .rds files for raster areas, and ice duration metrics. 

## General discussion 

Various docs along the way (to prove things) are in

```
inst/workflow/discussion
```

**Comment by mdsumner** [comment]
WIP

- [ ] static
- [ ] doc on bulk summary methods
- [ ] Gantt, coverage lines over time with different regions different colours, and gaps apropos
- [ ] clarify shoulder season pairs
- [ ] clarify terminology around density interpretation and usage

**Comment by mdsumner** [comment]
@RTreb @jessmt

I've changed the structure of the files, and cleaned up where the worker functions live. Just let me know if there's disruption with pull/merge :)

**Comment by RTreb** [comment]
It appears that the workflows folder has been moved out of the working directory. Need to confirm that the scripts in inst/workflows are the up-to-date version, and ensure documentation reflects this

**Comment by mdsumner** [comment]
Closing this, superseded by https://github.com/AustralianAntarcticDivision/aceecostats/issues/14
